{{- range $region := .Values.regions }}
{{- $instanceData := dict "dot" $ "regionPath" $region.path -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "visualizations.fullname" $instanceData }}
  labels:
    {{- include "visualizations.labels" $ | nindent 4 }}
    {{- include "visualizations.selectorLabels" $instanceData | nindent 4 }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - name: http
      port: {{ $.Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "visualizations.selectorLabels" $instanceData | nindent 4 }}
{{ end }}
